featured_category:
  type: integer
  default: 0
featured_tags:
  type: list
  list_type: tag
  default: "featured"
topic_source:
  type: enum
  default: "latest"
  choices:
    - latest
    - top/all
    - top/yearly
    - top/quarterly
    - top/monthly
    - top/weekly
    - top/daily
randomize_topics: true
display_when_unfiltered: true
display_on_categories: true
display_categories: 
  type: list
  list_type: category
  default: ""
maximum_topic_count: 6
scope_to_category: false
display_mobile: true
